CREATE TABLE game_info (
    id TEXT,
    game_str TEXT,
    home_team TEXT,
    away_team TEXT,
    at_bat TEXT,
    play_per_game INTEGER,
    inning INTEGER,
    top_bottom_inning TEXT,
    pitcher INTEGER,
    catcher INTEGER,
    first_base INTEGER,
    second_base INTEGER,
    third_base INTEGER,
    shortstop INTEGER,
    left_field INTEGER,
    center_field INTEGER,
    right_field INTEGER,
    batter INTEGER,
    first_baserunner INTEGER,
    second_baserunner INTEGER,
    third_baserunner INTEGER
);
